language: node_js

node_js:
  - "7"

sudo: false

install:
  - yarn global add codecov
  - yarn

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  - yarn run test
